### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by justeff** [hivemq/hivemq-extension-gradle-plugin#12]
## Expected behavior
Dependencies declared for unit tests are also usable for integration tests. For instance:
- testImplementation("org.wiremock:wiremock:3.7.0")

## Actual behavior
Dependencies are not furher shared and need to be redeclared if required for integration tests:
- testImplementation("org.wiremock:wiremock:3.7.0")
- integrationTestImplementation("org.wiremock:wiremock:3.7.0")

Is this a desired behavior or a bug? With _com.hivemq.extension_ **2.x** everything works as expected.

**Comment by SgtSilvio** [comment]
Hi @justeff 
yes, this is intended behavior.

This was one of the changes in the 3.x major version: https://github.com/hivemq/hivemq-extension-gradle-plugin/releases/tag/v3.0.0
> Remove integration test dependencies on main source set and test dependencies

Reason for this change:
- Following conventions: Gradle itself does not add dependencies to test suites other than unit tests: 
  > By convention, only the built-in test suite will automatically have a dependency on the production code of the project.

  (https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html#jvm_test_suite_plugin)
- Only white box tests such as unit tests should have access to the main source code
- You can still configure the dependencies between the test suites on your own if it is really required, but I would recommend  to avoid that
